
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://124.221.242.250:3306/usercenter?useSSL=false'
    username: dogyupi
    password: yupi666
  # session 失效时间
  session:
    timeout: 86400




